version: '3.8'
name: plagiarism_detection

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: plagiarism_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-plagiarism_db}
    ports:
      - "${PLAG_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    container_name: plagiarism_redis
    restart: always
    ports:
      - "${PLAG_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: plagiarism_minio
    restart: always
    ports:
      - "${PLAG_MINIO_API_PORT:-9000}:9000"
      - "${PLAG_MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data

  searxng:
    image: searxng/searxng:latest
    container_name: plagiarism_searxng
    restart: always
    volumes:
      - ./backend/searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  frontend:
    image: ${DOCKER_USERNAME}/plagiarism-frontend:latest
    container_name: plagiarism_frontend
    restart: always
    ports:
      - "${PLAG_FRONTEND_PORT:-8081}:80"
    depends_on:
      - api

  api:
    image: ${DOCKER_USERNAME}/plagiarism-api:latest
    container_name: plagiarism_api
    restart: always
    ports:
      - "${PLAG_API_PORT:-8001}:8000"
    depends_on:
      - db
      - redis
      - minio
      - searxng
    env_file:
      - .env

  celery-worker:
    image: ${DOCKER_USERNAME}/plagiarism-api:latest
    container_name: plagiarism_celery_worker
    restart: always
    command: celery -A app.core.celery.app worker -l info
    depends_on:
      - redis
      - api
    env_file:
      - .env

  celery-beat:
    image: ${DOCKER_USERNAME}/plagiarism-api:latest
    container_name: plagiarism_celery_beat
    restart: always
    command: celery -A app.core.celery.app beat -l info
    depends_on:
      - redis
      - api
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  minio_data:
